volumes: '3'

services:
  node:
    build: .
    networks:
      - user-net
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    restart: on-failure
      volumes:
        - ./src:/app/src
        - ./nodemon.json:/app/nodemon.json
        - ./logs:/app/logs
    environment:
      PORT: ${PORT}

  postgres:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - user-net

  networks:
    user-net:
      driver: bridge

  volumes:
    pgdata:
    # src:
    # logs:
